version: "3.9"

services:
  spark-driver:
    build:
      context: ./spark_driver
    volumes:
      - ./spark_driver:/spark-driver
      - ./spark-3.1.3-bin-hadoop3.2:/spark-driver/spark-3.1.3-bin-hadoop3.2
    depends_on:
      # - hadoop
      - kafka-server
      - kafka-publisher
      - spark-master
      - spark-worker-1
      - spark-worker-2
    environment:
      - SPARK_LOCAL_IP=localhost
      - PYSPARK_DRIVER_PYTHON=python3
      - PYSPARK_PYTHON=python3
    networks:
      - spark-kafka-cluster

  spark-master:
    build:
      context: ./spark_master
    ports:
      - '8080:8080'
    volumes:
      - ./spark-3.1.3-bin-hadoop3.2:/spark-master/spark-3.1.3-bin-hadoop3.2
    networks:
      - spark-kafka-cluster

  spark-worker-1:
    build:
      context: ./spark_worker
    volumes:
      - ./spark-3.1.3-bin-hadoop3.2:/spark-worker/spark-3.1.3-bin-hadoop3.2
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - '8081:8081'
    networks:
      - spark-kafka-cluster

  spark-worker-2:
    build:
      context: ./spark_worker
    volumes:
      - ./spark-3.1.3-bin-hadoop3.2:/spark-worker/spark-3.1.3-bin-hadoop3.2
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - '8082:8081'
    networks:
      - spark-kafka-cluster

  kafka-publisher:
    build:
      context: ./kafka_publisher
    depends_on:
      - kafka-server
    volumes:
      - ./kafka_publisher:/publisher
      - ./kafka_2.13-3.2.1:/publisher/kafka_2.13-3.2.1
    networks:
      - spark-kafka-cluster

  kafka-zookeeper:
    build:
      context: ./kafka_zookeeper
    volumes:
      - ./kafka_2.13-3.2.1:/kafka_zookeeper/kafka_2.13-3.2.1
    networks:
      - spark-kafka-cluster

  kafka-server:
    build:
      context: ./kafka_server
    depends_on:
      - kafka-zookeeper
    volumes:
      - ./kafka_2.13-3.2.1:/kafka_server/kafka_2.13-3.2.1
    networks:
      - spark-kafka-cluster

  # hadoop:
  #   image: cybermaggedon/hadoop


networks:
  spark-kafka-cluster:
    external: true
